server:
  port: 8080
spring:
  profiles:
    group:
      dev: h2
  application:
    name: eu-digital-green-certificates-verifier-service
  datasource:
    jndi-name: jdbc/dgc
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false
    change-log: classpath:db/changelog.xml
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  server:
    port: -1
dgc:
  certificatesDownloader:
    timeInterval: 60000
    lockLimit: 1800000
  gateway:
    connector:
      enabled: true
      endpoint: https://dgc-gateway.example.com
      proxy:
        enabled: false
      max-cache-age: 300
      tls-trust-store:
        password: dgcg-p4ssw0rd
        path: classpath:tls_trust_store.p12
      tls-key-store:
        alias: 1
        password: dgcg-p4ssw0rd
        path: classpath:tls_key_store.p12
      trust-anchor:
        alias: ta
        password: dgcg-p4ssw0rd
        path: classpath:trust_anchor.jks

springdoc:
  api-docs:
    enabled: false
